# Milestone 4 - My Project

## Author - Mike Pearson

## Instructions

1. Generate a clear statement problem and provide location for dataset
2. Provide a clear solution to the problem for a non-technical audience
3. Visually explore the data to generate insight and include summary statistics
4. Use an appropriate statistical analysis method
5. Prepare the data via cleaning, normalization, encoding, et cetera
6. Generate and evaluate a working model (hypothesis, linear, or time series)
7. Draw direct inferences and conclusions from model results
8. Use professional coding standards and techniques including:
        explanatory markdown text
        proper code comments
        functions to minimize redundant code
        minimize hard-coded variables

### Goal

I will examine the King's County Housing Data and see if I can come up with a model for predicting home prices.

In [76]:
fileName = "https://library.startlearninglabs.uw.edu/DATASCI410/Datasets/kc_house_data.csv"

In [77]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime as dt
import seaborn as sbn
from dateutil.parser import parse

In [78]:
Trippy = pd.read_csv(fileName)
Housing = pd.DataFrame(Trippy)
##print(Housing.tail())
##print(Housing.dtypes)
##print(Housing.describe())
##print(len(Housing))

## Make a TimeSeries

Add a column based on the 'date' column for datatime data to use in timeseries calculations, also make columns with just the year or month or day value.

Drop the 'date' column, the 'id column', the 'lat' and 'long' columns

In [79]:
end = len(Housing)- 1
for i in range(0, end):
    dummy = str(Housing.loc[i,'date'])
    dummy = dummy[0:8]
    mummy = dt.datetime.strptime(dummy,"%Y%m%d" )
    Housing.loc[i,'datetime']= mummy
    
Housing['year'] = Housing['date'].astype(str).str[0:4]
Housing['year'] = Housing['year'].astype(int)
Housing['month'] = Housing['date'].astype(str).str[4:6]
Housing['month'] = Housing['month'].astype(int)
Housing['day'] = Housing['date'].astype(str).str[6:8]
Housing['day'] = Housing['day'].astype(int)
Housing.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)
##Housing = Housing.drop('id', axis = 1)
##Housing = Housing.drop('date', axis = 1)
##Housing = Housing.drop('lat', axis = 1)
##Housing = Housing.drop('long', axis = 1)
##print(Housing.head(70))
##print(Housing.tail())
##print(Housing.dtypes)
##print(Housing.describe())

In [80]:
Housing.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)
Housing['dummy']= np.random.randint(1, 6, Housing.shape[0])
columnz = ['year','month', 'day', 'price']
Testy = pd.DataFrame([[2014, 5, 2, 100], [2014,5,3, 200],[2014,6,8]],columns = columnz)
##print(Testy)
##print(Testy.loc[Testy['day'] == 2])
Bob = Housing.loc[(Housing['day'] == 1) & (Housing['month'] == 5) & (Housing['year'] == 2014)]
##Testy.index.names(columnz)
trap = Testy.loc[(Testy['day'] == 2) & (Testy['month'] == 5) & (Testy['year'] == 2014)]
trip = trap['price']
##print("\nTrap is")
print(trap)
print(trip)
Bob['dummy'] = trip[0]
print(Housing.tail())
##Housing['dummy'] = np.where((Housing['month'] == Testy['month']) & (Housing['year'] == Testy['year']) & 
##                            (Housing['day'] == Testy['day']), Testy['price'], np.nan)
##bob = Housing.loc[(Housing['year'] == Testy[0,'year']) & (Housing['day'] == Testy[0,'day'])]
i= 1
##print(Testy.loc['year'])

   year  month  day  price
0  2014      5    2  100.0
0    100.0
Name: price, dtype: float64
               id             date      price  bedrooms  bathrooms  \
20472  5057100110  20150514T000000   479349.0         5       3.00
21450  8562790720  20150514T000000   749950.0         4       3.50
5637   7923600250  20150515T000000   450000.0         5       2.00
13053  5101400871  20150524T000000   445500.0         2       1.75
16594  9106000005  20150527T000000  1310000.0         4       2.25

       sqft_living  sqft_lot  floors  waterfront  view  ...    zipcode  \
20472         3223      6371     2.0           0     0  ...      98042
21450         2630      3757     2.0           0     0  ...      98027
5637          1870      7344     1.5           0     0  ...      98007
13053         1390      6670     1.0           0     0  ...      98115
16594         3750      5000     2.0           0     0  ...      98115

           lat     long  sqft_living15  sqft_lot15   datetime  year  month  \
20472  47.3584 -122.163           1979        9008 2015-05-14  2015      5
21450  47.5322 -122.075           2620        2699 2015-05-14  2015      5
5637   47.5951 -122.144           1870        7650 2015-05-15  2015      5
13053  47.6914 -122.308            920        6380 2015-05-24  2015      5
16594  47.6747 -122.303           2170        4590 2015-05-27  2015      5

       day  dummy
20472   14      1
21450   14      4
5637    15      2
13053   24      1
16594   27      5

[5 rows x 26 columns]

## Get the stock price data from Amazon, Starbucks, Boeing, Walmart, Microsoft and the Dow Jones Industrials

In [81]:
## Dow data

URL2 = 'https://raw.githubusercontent.com/mutecypher/DataSci-420/master/DJI.csv'
   
DJI = pd.read_csv(URL2)
##print(DJI.tail())
##print(DJI.dtypes)

## turn to data/time data

end = len(DJI)
DJI['year'] = np.random.randint(1,20,end)
DJI['month'] = np.random.randint(1,20,end)
DJI['day'] = np.random.randint(1,20,end)
for i in range(0, end):
    dummy = str(DJI.loc[i,'Date'])
    mummy = parse(dummy)
    DJI.loc[i,'datetime']= mummy
    DJI.loc[i,'year'] = mummy.year
    DJI.loc[i,'month'] = mummy.month
    DJI.loc[i,'day'] = mummy.day
DJI.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)
 ## Get the Amazon data   
print("\n after DJI",DJI.tail())   
URL3 = 'https://raw.githubusercontent.com/mutecypher/DataSci-420/master/AMZN.csv'
    

   
AMZN = pd.read_csv(URL3)

## turn to data/time data
print("\nBefore AMZN", AMZN.head())
end = len(AMZN)
AMZN['year'] = np.random.randint(1,20,end)
AMZN['month'] = np.random.randint(1,20,end)
AMZN['day'] = np.random.randint(1,20,end)
for i in range(0, end):
    dummy = str(AMZN.loc[i,'Date'])
    mummy = parse(dummy)
    AMZN.loc[i,'datetime']= mummy
    AMZN.loc[i,'year'] = mummy.year
    AMZN.loc[i,'month'] = mummy.month
    AMZN.loc[i,'day'] = mummy.day
AMZN.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)    
print("\nafter AMZN head is ", AMZN.head())  
    
## Get the Boeing data   
    
URL4 = 'https://raw.githubusercontent.com/mutecypher/DataSci-420/master/BA.csv'
    

   

BA = pd.read_csv(URL4)

## turn to data/time data

end = len(BA)
BA['year'] = np.random.randint(1,20,end)
BA['month'] = np.random.randint(1,20,end)
BA['day'] = np.random.randint(1,20,end)
for i in range(0, end):
    dummy = str(BA.loc[i,'Date'])
    mummy = parse(dummy)
    BA.loc[i,'datetime']= mummy
    BA.loc[i,'year'] = mummy.year
    BA.loc[i,'month'] = mummy.month
    BA.loc[i,'day'] = mummy.day
BA.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)    
   

## Get the Microsoft data

    
URL5 = 'https://raw.githubusercontent.com/mutecypher/DataSci-420/master/MSFT.csv'
    

MSFT = pd.read_csv(URL5)

## turn to data/time data

end = len(MSFT)
MSFT['year'] = np.random.randint(1,20,end)
MSFT['month'] = np.random.randint(1,20,end)
MSFT['day'] = np.random.randint(1,20,end)
for i in range(0, end):
    dummy = str(MSFT.loc[i,'Date'])
    mummy = parse(dummy)
    MSFT.loc[i,'datetime']= mummy
    MSFT.loc[i,'year'] = mummy.year
    MSFT.loc[i,'month'] = mummy.month
    MSFT.loc[i,'day'] = mummy.day
MSFT.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)    
   

## Get the Starbucks data

    
URL6 = 'https://raw.githubusercontent.com/mutecypher/DataSci-420/master/SBUX.csv'
    

SBUX = pd.read_csv(URL6)

## turn to data/time data

end = len(SBUX)
SBUX['year'] = np.random.randint(1,20,end)
SBUX['month'] = np.random.randint(1,20,end)
SBUX['day'] = np.random.randint(1,20,end)
for i in range(0, end):
    dummy = str(SBUX.loc[i,'Date'])
    mummy = parse(dummy)
    SBUX.loc[i,'datetime']= mummy
    SBUX.loc[i,'year'] = mummy.year
    SBUX.loc[i,'month'] = mummy.month
    SBUX.loc[i,'day'] = mummy.day
SBUX.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)    
   
## Get the Walmart data


    
URL7 = 'https://raw.githubusercontent.com/mutecypher/DataSci-420/master/WMT.csv'
    

WMT= pd.read_csv(URL7)

## turn to data/time data

end = len(WMT)
WMT['year'] = np.random.randint(1,20,end)
WMT['month'] = np.random.randint(1,20,end)
WMT['day'] = np.random.randint(1,20,end)
for i in range(0, end):
    dummy = str(WMT.loc[i,'Date'])
    mummy = parse(dummy)
    WMT.loc[i,'datetime']= mummy
    WMT.loc[i,'year'] = mummy.year
    WMT.loc[i,'month'] = mummy.month
    WMT.loc[i,'day'] = mummy.day
WMT.sort_values(['year','month', 'day'], ascending = (True, True, True), inplace = True)

 after DJI         Date         Open         High          Low        Close    Adj Close  \
264  5/20/15  18315.06055  18350.13086  18272.56055  18285.40039  18285.40039
265  5/21/15  18285.86914  18314.89063  18249.90039  18285.74023  18285.74023
266  5/22/15  18286.86914  18286.86914  18217.14063  18232.01953  18232.01953
267  5/26/15  18229.75000  18229.75000  17990.01953  18041.53906  18041.53906
268  5/27/15  18045.08008  18190.34961  18045.08008  18162.99023  18162.99023

        Volume  year  month  day   datetime
264   80190000  2015      5   20 2015-05-20
265   84270000  2015      5   21 2015-05-21
266   78890000  2015      5   22 2015-05-22
267  109440000  2015      5   26 2015-05-26
268   96400000  2015      5   27 2015-05-27

Before AMZN      Date        Open        High         Low       Close   Adj Close   Volume
0  5/2/14  310.420013  313.290009  304.309998  308.010010  308.010010  3995100
1  5/5/14  306.369995  310.230011  305.000000  310.049988  310.049988  2519900
2  5/6/14  309.529999  309.809998  297.040009  297.380005  297.380005  4682300
3  5/7/14  295.559998  296.399994  286.679993  292.709991  292.709991  7015200
4  5/8/14  290.820007  295.880005  287.230011  288.320007  288.320007  3848200

after AMZN head is       Date        Open        High         Low       Close   Adj Close  \
0  5/2/14  310.420013  313.290009  304.309998  308.010010  308.010010
1  5/5/14  306.369995  310.230011  305.000000  310.049988  310.049988
2  5/6/14  309.529999  309.809998  297.040009  297.380005  297.380005
3  5/7/14  295.559998  296.399994  286.679993  292.709991  292.709991
4  5/8/14  290.820007  295.880005  287.230011  288.320007  288.320007

    Volume  year  month  day   datetime
0  3995100  2014      5    2 2014-05-02
1  2519900  2014      5    5 2014-05-05
2  4682300  2014      5    6 2014-05-06
3  7015200  2014      5    7 2014-05-07
4  3848200  2014      5    8 2014-05-08

In [75]:
## for trying code

 after DJI         Date         Open         High          Low        Close    Adj Close  \
264  5/20/15  18315.06055  18350.13086  18272.56055  18285.40039  18285.40039
265  5/21/15  18285.86914  18314.89063  18249.90039  18285.74023  18285.74023
266  5/22/15  18286.86914  18286.86914  18217.14063  18232.01953  18232.01953
267  5/26/15  18229.75000  18229.75000  17990.01953  18041.53906  18041.53906
268  5/27/15  18045.08008  18190.34961  18045.08008  18162.99023  18162.99023

        Volume  year  month  day   datetime
264   80190000  2015      5   20 2015-05-20
265   84270000  2015      5   21 2015-05-21
266   78890000  2015      5   22 2015-05-22
267  109440000  2015      5   26 2015-05-26
268   96400000  2015      5   27 2015-05-27

In [82]:
## Now we add the stock data to the housing price data frame
All_data = pd.DataFrame()
dummy = pd.DataFrame()
of_it = len(AMZN)
for i in range(0,of_it):
    d = AMZN.loc[i,'day']
    m = AMZN.loc[i, 'month']
    y = AMZN.loc[i, 'year'] 
    dummy = Housing.loc[(Housing['day'] == d) & (Housing['month'] == m) & (Housing['year'] == y)]
    dummy['Amazon'] = AMZN.loc[i,'Close']
    dummy['Boeing'] = BA.loc[i,'Close']
    dummy['Microsoft'] = MSFT.loc[i,'Close']
    dummy['Starbucks'] = SBUX.loc[i,'Close']
    dummy['Walmart'] = WMT.loc[i,'Close']
    dummy['Dow Jones Industrial'] = DJI.loc[i,'Close']
    if (len(dummy) != 0):
         All_data = pd.concat([All_data, dummy])


print(All_data.dtypes)

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

id                               int64
date                            object
price                          float64
bedrooms                         int64
bathrooms                      float64
sqft_living                      int64
sqft_lot                         int64
floors                         float64
waterfront                       int64
view                             int64
condition                        int64
grade                            int64
sqft_above                       int64
sqft_basement                    int64
yr_built                         int64
yr_renovated                     int64
zipcode                          int64
lat                            float64
long                           float64
sqft_living15                    int64
sqft_lot15                       int64
datetime                datetime64[ns]
year                             int64
month                            int64
day                              int64
dummy                            int64
Amazon                         float64
Boeing                         float64
Microsoft                      float64
Starbucks                      float64
Walmart                        float64
Dow Jones Industrial           float64
dtype: object

## Make a quick time series plot

## Summary


We have looked at various parameters involved in pricing and seen that waterfront versus not waterfront is very different. We have determined that there is not a lot of seasonality in the data on pricing (for the relatively short season).  

We have created a model for the pricing (normed pricing) and seen that pricing can be modestly predicted based on square footage of living space, view, number of bedrooms, the age of the house, and the zip code. Anyone wanting to predict a selling price can use the model res.predict in the next to last section.

In [84]:
##print(Housing.describe())
##print(All_data.describe())
d = 2
m = 5
y = 2014
dummy = All_data.loc[(All_data['day'] == d)]
print(dummy)

               id             date      price  bedrooms  bathrooms  \
172    1999700045  20140502T000000   313000.0         3       1.50
312    1860600135  20140502T000000  2384000.0         5       2.50
502    5467900070  20140502T000000   342000.0         3       2.00
775    4040800810  20140502T000000   420000.0         3       2.25
1041   7197300105  20140502T000000   550000.0         4       2.50
1393   5100401414  20140502T000000   490000.0         2       1.00
2487   7525100520  20140502T000000   335000.0         2       2.00
2580   2591720070  20140502T000000   482000.0         4       2.50
3323   1323089184  20140502T000000   452500.0         3       2.50
3714   6127600110  20140502T000000   640000.0         4       2.00
3723   7739100015  20140502T000000   463000.0         3       1.75
4335   4217401055  20140502T000000  1400000.0         4       2.50
4964   7525000080  20140502T000000   588500.0         3       1.75
5002   3390600010  20140502T000000   365000.0         3       1.00
5043   4219400290  20140502T000000  1200000.0         5       2.75
5613   2618300080  20140502T000000   242500.0         3       1.50
5657   2207200675  20140502T000000   419000.0         3       1.50
5956   3328500250  20140502T000000   285000.0         4       2.50
6311   6600780130  20140502T000000   367500.0         4       3.00
6424   2011000010  20140502T000000   257950.0         3       1.75
6661    776600130  20140502T000000   275000.0         3       1.50
6711   5652600185  20140502T000000   750000.0         3       1.75
7323   2202500290  20140502T000000   435000.0         4       1.00
7734   1962200037  20140502T000000   626000.0         3       2.25
7942   1088800850  20140502T000000   612500.0         4       2.50
7961   5101405331  20140502T000000   495000.0         4       1.75
8300   7575600100  20140502T000000   285000.0         3       2.50
8326   2493200195  20140502T000000   615000.0         3       1.75
8892   1245003160  20140502T000000   698000.0         4       2.25
9587   1024069009  20140502T000000   675000.0         5       2.50
...           ...              ...        ...       ...        ...
14716  1922000180  20150402T000000  1160000.0         4       3.75
14885  8673400177  20150402T000000   525000.0         3       3.00
14901  1125079088  20150402T000000   455000.0         2       1.00
14912  2926049504  20150402T000000   500000.0         3       2.25
14928  1513800170  20150402T000000   392500.0         3       1.00
14979  1982200480  20150402T000000   724950.0         4       2.50
15163  2848700095  20150402T000000   412000.0         4       1.50
15323  2922701305  20150402T000000   470000.0         2       1.75
16126  1725059252  20150402T000000   550000.0         4       3.50
17063  2815600235  20150402T000000   450600.0         2       1.00
17070   766900250  20150402T000000   406000.0         3       1.75
17108  4023500362  20150402T000000   540000.0         4       1.75
17184  3449820380  20150402T000000   564450.0         3       2.50
17345  7852020670  20150402T000000   475000.0         3       2.75
17784  7763400035  20150402T000000   253500.0         3       1.50
17810  1323059098  20150402T000000   315000.0         3       2.00
18329  3365900175  20150402T000000   424305.0         3       2.50
18586   522049122  20150402T000000   195000.0         4       1.75
18682  2592401080  20150402T000000   525000.0         3       2.50
18948  3982700088  20150402T000000   910000.0         3       2.50
19534  5078400035  20150402T000000   875000.0         4       1.75
19863  2768100510  20150402T000000   649000.0         3       2.00
20212  6601200250  20150402T000000   205000.0         4       2.50
20389  7548301050  20150402T000000   390000.0         2       1.50
20460  9808100150  20150402T000000  3345000.0         5       3.75
20587  7518507055  20150402T000000   855000.0         4       3.25
20746  3166900270  20150402T000000   391500.0         3       2.50
21022  2597490410  20150402T000000   740000.0         3       2.50
21193  2770601912  20150402T000000   570000.0         3       3.25
21338   525049174  20150402T000000   435000.0         3       1.50

       sqft_living  sqft_lot  floors  waterfront  view          ...           \
172           1340      7912     1.5           0     0          ...
312           3650      9050     2.0           0     4          ...
502           1930     11947     1.0           0     0          ...
775           2000      8030     1.0           0     0          ...
1041          1940     10500     1.0           0     0          ...
1393           880      6380     1.0           0     0          ...
2487          1350      2560     1.0           0     0          ...
2580          2710     35868     2.0           0     0          ...
3323          2430     88426     1.0           0     0          ...
3714          1520      6200     1.5           0     0          ...
3723          1710      7320     1.0           0     0          ...
4335          2920      4000     1.5           0     0          ...
4964          2330     14892     1.0           0     0          ...
5002          1090      6435     1.0           0     0          ...
5043          2910      9480     1.5           0     0          ...
5613          1200      9720     1.0           0     0          ...
5657          1570      6700     1.0           0     0          ...
5956          2200      9397     2.0           0     0          ...
6311          3110      7231     2.0           0     0          ...
6424          1370      5858     1.0           0     0          ...
6661          1180     10277     1.0           0     0          ...
6711          2240     10578     2.0           0     0          ...
7323          1450      8800     1.0           0     0          ...
7734          1750      1572     2.5           0     0          ...
7942          2730     12261     2.0           0     0          ...
7961          1600      6380     1.0           0     0          ...
8300          2090     10834     1.0           0     0          ...
8326          2360      7291     1.0           0     0          ...
8892          2200     11250     1.5           0     0          ...
9587          2820     67518     2.0           0     0          ...
...            ...       ...     ...         ...   ...          ...
14716         3560     13959     2.0           0     0          ...
14885         1730      1074     3.5           0     0          ...
14901         1330     92782     1.0           0     0          ...
14912         1700      9008     1.0           0     0          ...
14928          930      6572     1.0           0     0          ...
14979         2860      3638     1.5           0     2          ...
15163         1960      5000     1.0           0     0          ...
15323         1520      4220     1.0           0     0          ...
16126         2770     24140     2.0           0     0          ...
17063          840      7020     1.5           0     0          ...
17070         1270      6017     1.0           0     0          ...
17108         2040      9322     1.0           0     0          ...
17184         2710      6174     2.0           0     0          ...
17345         1890      3938     2.0           0     0          ...
17784         1440     12040     1.0           0     0          ...
17810         1220     14645     1.0           0     0          ...
18329         1600      5960     2.0           0     2          ...
18586         1320      7694     1.0           0     0          ...
18682         1720      7950     1.5           0     0          ...
18948         2720      7250     2.0           0     0          ...
19534         2360      8286     1.0           0     0          ...
19863         1530      1442     3.0           0     0          ...
20212         1767      4500     2.0           0     0          ...
20389         1340      1402     2.0           0     0          ...
20460         5350     15360     1.0           0     1          ...
20587         2630      2550     2.0           0     0          ...
20746         2424      6143     2.0           0     0          ...
21022         2350      3798     2.0           0     0          ...
21193         1550      1280     2.0           0     0          ...
21338         1180      1231     3.0           0     0          ...

       year  month  day  dummy     Amazon      Boeing  Microsoft  Starbucks  \
172    2014      5    2      2  308.01001  129.940002  39.689999  35.299999
312    2014      5    2      1  308.01001  129.940002  39.689999  35.299999
502    2014      5    2      2  308.01001  129.940002  39.689999  35.299999
775    2014      5    2      4  308.01001  129.940002  39.689999  35.299999
1041   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
1393   2014      5    2      5  308.01001  129.940002  39.689999  35.299999
2487   2014      5    2      2  308.01001  129.940002  39.689999  35.299999
2580   2014      5    2      1  308.01001  129.940002  39.689999  35.299999
3323   2014      5    2      3  308.01001  129.940002  39.689999  35.299999
3714   2014      5    2      3  308.01001  129.940002  39.689999  35.299999
3723   2014      5    2      5  308.01001  129.940002  39.689999  35.299999
4335   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
4964   2014      5    2      3  308.01001  129.940002  39.689999  35.299999
5002   2014      5    2      3  308.01001  129.940002  39.689999  35.299999
5043   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
5613   2014      5    2      1  308.01001  129.940002  39.689999  35.299999
5657   2014      5    2      1  308.01001  129.940002  39.689999  35.299999
5956   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
6311   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
6424   2014      5    2      1  308.01001  129.940002  39.689999  35.299999
6661   2014      5    2      3  308.01001  129.940002  39.689999  35.299999
6711   2014      5    2      1  308.01001  129.940002  39.689999  35.299999
7323   2014      5    2      5  308.01001  129.940002  39.689999  35.299999
7734   2014      5    2      2  308.01001  129.940002  39.689999  35.299999
7942   2014      5    2      1  308.01001  129.940002  39.689999  35.299999
7961   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
8300   2014      5    2      5  308.01001  129.940002  39.689999  35.299999
8326   2014      5    2      5  308.01001  129.940002  39.689999  35.299999
8892   2014      5    2      5  308.01001  129.940002  39.689999  35.299999
9587   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
...     ...    ...  ...    ...        ...         ...        ...        ...
14716  2015      4    2      2  372.25000  149.279999  40.290001  47.195000
14885  2015      4    2      1  372.25000  149.279999  40.290001  47.195000
14901  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
14912  2015      4    2      4  372.25000  149.279999  40.290001  47.195000
14928  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
14979  2015      4    2      4  372.25000  149.279999  40.290001  47.195000
15163  2015      4    2      2  372.25000  149.279999  40.290001  47.195000
15323  2015      4    2      2  372.25000  149.279999  40.290001  47.195000
16126  2015      4    2      4  372.25000  149.279999  40.290001  47.195000
17063  2015      4    2      5  372.25000  149.279999  40.290001  47.195000
17070  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
17108  2015      4    2      5  372.25000  149.279999  40.290001  47.195000
17184  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
17345  2015      4    2      1  372.25000  149.279999  40.290001  47.195000
17784  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
17810  2015      4    2      2  372.25000  149.279999  40.290001  47.195000
18329  2015      4    2      2  372.25000  149.279999  40.290001  47.195000
18586  2015      4    2      5  372.25000  149.279999  40.290001  47.195000
18682  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
18948  2015      4    2      1  372.25000  149.279999  40.290001  47.195000
19534  2015      4    2      2  372.25000  149.279999  40.290001  47.195000
19863  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
20212  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
20389  2015      4    2      2  372.25000  149.279999  40.290001  47.195000
20460  2015      4    2      5  372.25000  149.279999  40.290001  47.195000
20587  2015      4    2      1  372.25000  149.279999  40.290001  47.195000
20746  2015      4    2      5  372.25000  149.279999  40.290001  47.195000
21022  2015      4    2      3  372.25000  149.279999  40.290001  47.195000
21193  2015      4    2      4  372.25000  149.279999  40.290001  47.195000
21338  2015      4    2      1  372.25000  149.279999  40.290001  47.195000

         Walmart  Dow Jones Industrial
172    79.120003           16512.89063
312    79.120003           16512.89063
502    79.120003           16512.89063
775    79.120003           16512.89063
1041   79.120003           16512.89063
1393   79.120003           16512.89063
2487   79.120003           16512.89063
2580   79.120003           16512.89063
3323   79.120003           16512.89063
3714   79.120003           16512.89063
3723   79.120003           16512.89063
4335   79.120003           16512.89063
4964   79.120003           16512.89063
5002   79.120003           16512.89063
5043   79.120003           16512.89063
5613   79.120003           16512.89063
5657   79.120003           16512.89063
5956   79.120003           16512.89063
6311   79.120003           16512.89063
6424   79.120003           16512.89063
6661   79.120003           16512.89063
6711   79.120003           16512.89063
7323   79.120003           16512.89063
7734   79.120003           16512.89063
7942   79.120003           16512.89063
7961   79.120003           16512.89063
8300   79.120003           16512.89063
8326   79.120003           16512.89063
8892   79.120003           16512.89063
9587   79.120003           16512.89063
...          ...                   ...
14716  80.730003           17763.24023
14885  80.730003           17763.24023
14901  80.730003           17763.24023
14912  80.730003           17763.24023
14928  80.730003           17763.24023
14979  80.730003           17763.24023
15163  80.730003           17763.24023
15323  80.730003           17763.24023
16126  80.730003           17763.24023
17063  80.730003           17763.24023
17070  80.730003           17763.24023
17108  80.730003           17763.24023
17184  80.730003           17763.24023
17345  80.730003           17763.24023
17784  80.730003           17763.24023
17810  80.730003           17763.24023
18329  80.730003           17763.24023
18586  80.730003           17763.24023
18682  80.730003           17763.24023
18948  80.730003           17763.24023
19534  80.730003           17763.24023
19863  80.730003           17763.24023
20212  80.730003           17763.24023
20389  80.730003           17763.24023
20460  80.730003           17763.24023
20587  80.730003           17763.24023
20746  80.730003           17763.24023
21022  80.730003           17763.24023
21193  80.730003           17763.24023
21338  80.730003           17763.24023

[725 rows x 32 columns]

In [89]:
print(All_data.shape)
print(Housing.shape)

(20991, 32)
(21613, 26)

In [91]:
y = 2014
weekend_data = pd.DataFrame()
stock_data = pd.DataFrame()
houses_closed = pd.DataFrame()
months = [5,6,7,8,9,10,11,12]
days = np.arange(2,32)
for m in months:
    for d in days:
        stock_data = All_data.loc[(All_data['day'] == d) & (All_data['month'] == m) & (All_data['year'] == y)]
        if stock_data.empty ==  True:
            houses_closed = Housing.loc[(Housing['day'] == d) & (Housing['month'] == m) & (Housing['year'] == y)]
            if houses_closed.empty ==  False:
                weekend_data = houses_closed
                if d != 1:
                    prev_day_stock = All_data.loc[(All_data['day'] == (d - 1)) & (All_data['month'] == m) & (All_data['year'] == y)]
                    weekend_data['Amazon'] = prev_day_stock.loc['Amazon']
                    weekend_data['Boeing'] = prev_day_stock['Boeing']
                    weekend_data['Microsoft'] = prev_day_stock['Microsoft']
                    weekend_data['Starbucks'] = prev_day_stock['Starbucks']
                    weekend_data['Walmart'] = prev_day_stock['Walmart']
                    weekend_data['Dow Jones Industrial'] = prev_day_stock['Dow Jones Industrial']
                    All_data = pd.concat([All_data, weekend_data])
## Deal with the possibility that Saturday or Sunday may be the first day of the month, so go back one day 
## 31 of previous month
                else:
                    prev_day_stock = All_data.loc[(All_data['day'] == 31) & (All_data['month'] == m - 1) & (All_data['year'] == y)]
                    if prev_day_stock.empty == False:
                        weekend_data['Amazon'] = prev_day_stock['Amazon']
                        weekend_data['Boeing'] = prev_day_stock['Boeing']
                        weekend_data['Microsoft'] = prev_day_stock['Microsoft']
                        weekend_data['Starbucks'] = prev_day_stock['Starbucks']
                        weekend_data['Walmart'] = prev_day_stock['Walmart']
                        weekend_data['Dow Jones Industrial'] = prev_day_stock['Dow Jones Industrial']
                        All_data = pd.concat([All_data, weekend_data])
## Or possibly the 30th of the month
                    else:
                        prev_day_stock = All_data.loc[(All_data['day'] == 30) & (All_data['month'] == m - 1) & (All_data['year'] == y)]
                        if prev_day_stock.empty == False:
                            weekend_data['Amazon'] = prev_day_stock['Amazon']
                            weekend_data['Boeing'] = prev_day_stock['Boeing']
                            weekend_data['Microsoft'] = prev_day_stock['Microsoft']
                            weekend_data['Starbucks'] = prev_day_stock['Starbucks']
                            weekend_data['Walmart'] = prev_day_stock['Walmart']
                            weekend_data['Dow Jones Industrial'] = prev_day_stock['Dow Jones Industrial']
                            All_data = pd.concat([All_data, weekend_data])

KeyError: 'the label [Amazon] is not in the [index]'

In [97]:
##print(All_data.describe())
prev_day_stock = pd.DataFrame()
prev_day_stock = All_data.loc[(All_data['day'] == 2) & (All_data['month'] == 5) & (All_data['year'] == 2014)]
print(prev_day_stock["Amazon"])
print(d, m ,y)
print(All_data.head())

172      308.01001
312      308.01001
502      308.01001
775      308.01001
1041     308.01001
1393     308.01001
2487     308.01001
2580     308.01001
3323     308.01001
3714     308.01001
3723     308.01001
4335     308.01001
4964     308.01001
5002     308.01001
5043     308.01001
5613     308.01001
5657     308.01001
5956     308.01001
6311     308.01001
6424     308.01001
6661     308.01001
6711     308.01001
7323     308.01001
7734     308.01001
7942     308.01001
7961     308.01001
8300     308.01001
8326     308.01001
8892     308.01001
9587     308.01001
           ...
12366    308.01001
12496    308.01001
13108    308.01001
13648    308.01001
13980    308.01001
14088    308.01001
14817    308.01001
15127    308.01001
15556    308.01001
15921    308.01001
16316    308.01001
16768    308.01001
16880    308.01001
16923    308.01001
17038    308.01001
17055    308.01001
17400    308.01001
17402    308.01001
17480    308.01001
18690    308.01001
19066    308.01001
19566    308.01001
19677    308.01001
19830    308.01001
20149    308.01001
20559    308.01001
20602    308.01001
21161    308.01001
21287    308.01001
21390    308.01001
Name: Amazon, Length: 67, dtype: float64
3 5 2014
              id             date      price  bedrooms  bathrooms  \
172   1999700045  20140502T000000   313000.0         3       1.50
312   1860600135  20140502T000000  2384000.0         5       2.50
502   5467900070  20140502T000000   342000.0         3       2.00
775   4040800810  20140502T000000   420000.0         3       2.25
1041  7197300105  20140502T000000   550000.0         4       2.50

      sqft_living  sqft_lot  floors  waterfront  view          ...           \
172          1340      7912     1.5           0     0          ...
312          3650      9050     2.0           0     4          ...
502          1930     11947     1.0           0     0          ...
775          2000      8030     1.0           0     0          ...
1041         1940     10500     1.0           0     0          ...

      year  month  day  dummy     Amazon      Boeing  Microsoft  Starbucks  \
172   2014      5    2      2  308.01001  129.940002  39.689999  35.299999
312   2014      5    2      1  308.01001  129.940002  39.689999  35.299999
502   2014      5    2      2  308.01001  129.940002  39.689999  35.299999
775   2014      5    2      4  308.01001  129.940002  39.689999  35.299999
1041  2014      5    2      4  308.01001  129.940002  39.689999  35.299999

        Walmart  Dow Jones Industrial
172   79.120003           16512.89063
312   79.120003           16512.89063
502   79.120003           16512.89063
775   79.120003           16512.89063
1041  79.120003           16512.89063

[5 rows x 32 columns]

In [ ]:
                    weekend_data['Amazon'] = prev_day_stock.loc['Amazon']
                    weekend_data['Boeing'] = prev_day_stock['Boeing']
                    weekend_data['Microsoft'] = prev_day_stock['Microsoft']
                    weekend_data['Starbucks'] = prev_day_stock['Starbucks']
                    weekend_data['Walmart'] = prev_day_stock['Walmart']
                    weekend_data['Dow Jones Industrial'] = prev_day_stock['Dow Jones Industrial']
                    All_data = pd.concat([All_data, weekend_data])
## Deal with the possibility that Saturday or Sunday may be the first day of the month, so go back one day 
## 31 of previous month
                else:
                    prev_day_stock = All_data.loc[(All_data['day'] == 31) & (All_data['month'] == m - 1) & (All_data['year'] == y)]
                    if prev_day_stock.empty == False:
                        weekend_data['Amazon'] = prev_day_stock['Amazon']
                        weekend_data['Boeing'] = prev_day_stock['Boeing']
                        weekend_data['Microsoft'] = prev_day_stock['Microsoft']
                        weekend_data['Starbucks'] = prev_day_stock['Starbucks']
                        weekend_data['Walmart'] = prev_day_stock['Walmart']
                        weekend_data['Dow Jones Industrial'] = prev_day_stock['Dow Jones Industrial']
                        All_data = pd.concat([All_data, weekend_data])
## Or possibly the 30th of the month
                    else:
                        prev_day_stock = All_data.loc[(All_data['day'] == 30) & (All_data['month'] == m - 1) & (All_data['year'] == y)]
                        if prev_day_stock.empty == False:
                            weekend_data['Amazon'] = prev_day_stock['Amazon']
                            weekend_data['Boeing'] = prev_day_stock['Boeing']
                            weekend_data['Microsoft'] = prev_day_stock['Microsoft']
                            weekend_data['Starbucks'] = prev_day_stock['Starbucks']
                            weekend_data['Walmart'] = prev_day_stock['Walmart']
                            weekend_data['Dow Jones Industrial'] = prev_day_stock['Dow Jones Industrial']
                            All_data = pd.concat([All_data, weekend_data])